// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACxf_wxJE9hoqsXMV5b9HAn9McMh7pqGY',
    appId: '1:241981984767:web:4d327655f1f38c207861ca',
    messagingSenderId: '241981984767',
    projectId: 'online-app-store-7558b',
    authDomain: 'online-app-store-7558b.firebaseapp.com',
    storageBucket: 'online-app-store-7558b.appspot.com',
    databaseURL:
        "https://online-app-store-7558b-default-rtdb.asia-southeast1.firebasedatabase.app",
    measurementId: 'G-M3W0YY16EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDriepMxNSkHTo5ZoBZgCV-jsTnCq-6TxU',
    appId: '1:241981984767:android:ec8199569ec446117861ca',
    messagingSenderId: '241981984767',
    projectId: 'online-app-store-7558b',
    databaseURL:
        "https://online-app-store-7558b-default-rtdb.asia-southeast1.firebasedatabase.app",
    storageBucket: 'online-app-store-7558b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_E8s6DMPjLM9irM4iJkb-wgIUzzJYv2M',
    appId: '1:241981984767:ios:0d0f31f02e14d7a97861ca',
    messagingSenderId: '241981984767',
    projectId: 'online-app-store-7558b',
    storageBucket: 'online-app-store-7558b.appspot.com',
    databaseURL:
        "https://online-app-store-7558b-default-rtdb.asia-southeast1.firebasedatabase.app",
    iosBundleId: 'com.example.onlineAppFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_E8s6DMPjLM9irM4iJkb-wgIUzzJYv2M',
    appId: '1:241981984767:ios:0d0f31f02e14d7a97861ca',
    messagingSenderId: '241981984767',
    projectId: 'online-app-store-7558b',
    storageBucket: 'online-app-store-7558b.appspot.com',
    databaseURL:
        "https://online-app-store-7558b-default-rtdb.asia-southeast1.firebasedatabase.app",
    iosBundleId: 'com.example.onlineAppFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACxf_wxJE9hoqsXMV5b9HAn9McMh7pqGY',
    appId: '1:241981984767:web:b943a474f90ae9f77861ca',
    messagingSenderId: '241981984767',
    projectId: 'online-app-store-7558b',
    authDomain: 'online-app-store-7558b.firebaseapp.com',
    databaseURL:
        "https://online-app-store-7558b-default-rtdb.asia-southeast1.firebasedatabase.app",
    storageBucket: 'online-app-store-7558b.appspot.com',
    measurementId: 'G-PGJVCB49QB',
  );
}
